In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, LabelBinarizer
import numpy as np

In [3]:
a = ['cold','hot','warm','warm','hot','hot','cold','warm']

In [4]:
LE = LabelEncoder()
LE.fit_transform(a)

array([0, 1, 2, 2, 1, 1, 0, 2], dtype=int64)

In [13]:
ohe = OneHotEncoder(sparse = False)
a_ohe = np.array(a).reshape(-1,1)
ohe.fit_transform(a_ohe)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [17]:
lb = LabelBinarizer()
lb.fit_transform(a)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]])

In [18]:
##multicolumn output
X = [["US", "M"], ["UK", "M"], ["FR", "F"]]


In [19]:
ohe.fit_transform(X)

array([[0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0.]])

In [20]:
##multi target output is not supported in label binarizer and label encoder whereas ohe supports
lb.fit_transform(X)

ValueError: Multioutput target data is not supported with label binarization

In [21]:
LE.fit_transform(X)

ValueError: bad input shape (3, 2)